### PR TITLE
Add sunsetOrange color palette

### PR DESCRIPTION
**Pull request by kartikcho**
Updated `customColors.js` to house shades of sunsetOrange.

### CODE REVIEW

**Review by sauravhiremath — CHANGES_REQUESTED** [review]
LGTM

Can u change the primary and secondary color to `sunsetOrange` shades inside `theme.js`?

**Comment by kartikcho** [comment]
> ...inside theme.js?

I can't find `theme.js`, can you link to it?

**Review by sauravhiremath — COMMENTED** [review]
Can we create a separate PR for linting changes? 

Too much diff for reviewing the primary changes

**Review by sauravhiremath — CHANGES_REQUESTED** [review]
Some changes required

- `src/theme/index.js` - `L2`

  ```javascript
  import { sunsetOrange } from './customColors';
  ```
- `src/theme/index.js` - `L13`

  ```javascript
  main: sunsetOrange[600]
  ```
- `src/theme/index.js` - `L16`

  ```javascript
  main: sunsetOrange[400]
  ```

Also need to update, hex color codes in `login.module.scss`

**Comment by kartikcho** [comment]
The hexes have been switched to using theme variables, although there are not much noticeable visual design changes @sauravhiremath . 

image

**Review by sauravhiremath — APPROVED** [review]
LGTM

**Pull request merged**
